from __future__ import annotations

import os
import time
from datetime import datetime

from src.mcp_server.protocol import ECOMCPServer


MOCK_SCENARIOS: dict[str, dict] = {
    "happy_path": {
        "run_eco_route":  {"route_done": True},
        "run_ext":        {"ext_done": True},
        "run_sta":        {"setup_vio": 125, "hold_vio": 47},
        "run_pv":         {"pv_pass": True},
        "run_signoff":    {"signoff_pass": True, "violations": []},
        "run_fix_setup":  {"fix_done": True, "setup_vio": 30},
        "run_fix_hold":   {"fix_done": True, "hold_vio": 10},
        "run_fix_leakage": {"fix_done": True},
    },
    "convergence": {
        "run_eco_route":  {"route_done": True},
        "run_ext":        {"ext_done": True},
        "run_sta":        {"setup_vio": 80, "hold_vio": 25},
        "run_pv":         {"pv_pass": True},
        "run_signoff":    {"signoff_pass": True, "violations": []},
        "run_fix_setup":  {"fix_done": True, "setup_vio": 15},
        "run_fix_hold":   {"fix_done": True, "hold_vio": 5},
        "run_fix_leakage": {"fix_done": True},
    },
    "phase1_ext_error": {
        "run_eco_route":  {"route_done": True},
        "run_ext":        "raise Exception('StarRCX license 失效')",
    },
    "phase2_sta_error": {
        "run_eco_route":  {"route_done": True},
        "run_ext":        {"ext_done": True},
        "run_sta":        "raise Exception('STA 执行超时（超时时间1800s），进程被强制终止')",
        "run_pv":         {"pv_pass": True},
        "run_signoff":    {"signoff_pass": True, "violations": []},
    },
    "phase2_pv_error": {
        "run_eco_route":  {"route_done": True},
        "run_ext":        {"ext_done": True},
        "run_sta":        {"setup_vio": 125, "hold_vio": 47},
        "run_pv":         "raise Exception('PV LVS 检查失败，netlist mismatch')",
        "run_signoff":    {"signoff_pass": True, "violations": []},
    },
    "phase2_signoff_error": {
        "run_eco_route":  {"route_done": True},
        "run_ext":        {"ext_done": True},
        "run_sta":        {"setup_vio": 125, "hold_vio": 47},
        "run_pv":         {"pv_pass": True},
        "run_signoff":    "raise Exception('Signoff DRC 检查失败，mask violation')",
    },
    "phase3_fix_error": {
        "run_eco_route":  {"route_done": True},
        "run_ext":        {"ext_done": True},
        "run_sta":        {"setup_vio": 125, "hold_vio": 47},
        "run_pv":         {"pv_pass": True},
        "run_signoff":    {"signoff_pass": True, "violations": []},
        "run_fix_setup":  "raise Exception('ECO Fix 工具异常，setup 无法进一步收敛')",
        "run_fix_hold":   "raise Exception('ECO Fix 工具异常，hold 无法进一步收敛')",
    },
}

STEP_LABELS: dict[str, str] = {
    "run_eco_route": "Route (Innovus)",
    "run_ext": "Parasitic Extraction (StarRCX)",
    "run_sta": "Static Timing Analysis (PrimeTime)",
    "run_pv": "Physical Verification (Calibre)",
    "run_signoff": "Signoff Check",
    "run_fix_setup": "ECO Fix - Setup",
    "run_fix_hold": "ECO Fix - Hold",
    "run_fix_leakage": "ECO Fix - Leakage",
}


class MockECOMCPServer(ECOMCPServer):

    def __init__(self, scenario: str = "happy_path", simulate_delay: float = 0.3):
        self.scenario = scenario
        self.delay = simulate_delay
        self.execution_log: list[dict] = []

    def _write_log(self, run_dir: str, step_name: str, status: str, message: str):
        try:
            os.makedirs(run_dir, exist_ok=True)
            ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            log_path = os.path.join(run_dir, f"{step_name}.log")
            label = STEP_LABELS.get(step_name, step_name)

            with open(log_path, "w") as f:
                f.write(f"{'='*60}\n")
                f.write(f"  {label}  ({step_name})\n")
                f.write(f"  Timestamp : {ts}\n")
                f.write(f"  Scenario  : {self.scenario}\n")
                f.write(f"  Status    : {status}\n")
                f.write(f"{'='*60}\n\n")
                f.write(message.rstrip() + "\n\n")

            rpt_path = os.path.join(run_dir, f"{step_name}.rpt")
            self._write_rpt(rpt_path, step_name, message)
        except OSError:
            pass

    def _write_rpt(self, rpt_path: str, step_name: str, raw_msg: str):
        label = STEP_LABELS.get(step_name, step_name)
        try:
            with open(rpt_path, "w") as f:
                f.write(f"* Mock ECO Report :: {label} *\n")
                f.write(f"* Generated by MockECOMCPServer  *\n\n")
                for line in raw_msg.splitlines():
                    f.write(f"  {line}\n")
        except OSError:
            pass

    def _build_step_output(self, step_name: str, success: bool, data: dict | str) -> str:
        label = STEP_LABELS.get(step_name, step_name)
        lines = [f"[{step_name}] {label}"]

        if not success:
            msg = data if isinstance(data, str) else str(data)
            lines.append(f"ERROR: {msg}")
            lines.append(f"Exit code: non-zero")
            lines.append(f"Tool terminated abnormally")
        else:
            lines.append(f"Exit code: 0")
            lines.append(f"Execution finished normally")
            if isinstance(data, dict):
                for k, v in data.items():
                    lines.append(f"  {k} = {v}")
        return "\n".join(lines)

    def _execute(self, step_name: str, design_name: str = "", run_dir: str = "", **kwargs) -> dict:
        started_at = datetime.now()
        time.sleep(self.delay)

        scenario_data = MOCK_SCENARIOS.get(self.scenario, {})
        val = scenario_data.get(step_name)
        if val is None:
            val = MOCK_SCENARIOS["happy_path"].get(step_name, {})

        if isinstance(val, str) and val.startswith("raise"):
            msg = val.split("'", 1)[1].rsplit("'", 1)[0]
            output = self._build_step_output(step_name, False, msg)
            if run_dir:
                self._write_log(run_dir, step_name, "ERROR", output)
            self.execution_log.append({
                "step": step_name,
                "design": design_name,
                "run_dir": run_dir,
                "status": "error",
                "elapsed_s": (datetime.now() - started_at).total_seconds(),
            })
            raise Exception(msg)

        output = self._build_step_output(step_name, True, val)
        if run_dir:
            self._write_log(run_dir, step_name, "DONE", output)
        self.execution_log.append({
            "step": step_name,
            "design": design_name,
            "run_dir": run_dir,
            "status": "done",
            "elapsed_s": (datetime.now() - started_at).total_seconds(),
        })
        return val

    def run_eco_route(self, design_name: str, run_dir: str) -> dict:
        return self._execute("run_eco_route", design_name=design_name, run_dir=run_dir)

    def run_ext(self, design_name: str, run_dir: str) -> dict:
        return self._execute("run_ext", design_name=design_name, run_dir=run_dir)

    def run_sta(self, design_name: str, run_dir: str) -> dict:
        return self._execute("run_sta", design_name=design_name, run_dir=run_dir)

    def run_pv(self, design_name: str, run_dir: str) -> dict:
        return self._execute("run_pv", design_name=design_name, run_dir=run_dir)

    def run_signoff(self, design_name: str, run_dir: str) -> dict:
        return self._execute("run_signoff", design_name=design_name, run_dir=run_dir)

    def run_fix_setup(self, design_name: str, run_dir: str, fix_strategy: str) -> dict:
        return self._execute("run_fix_setup", design_name=design_name, run_dir=run_dir, fix_strategy=fix_strategy)

    def run_fix_hold(self, design_name: str, run_dir: str, fix_strategy: str) -> dict:
        return self._execute("run_fix_hold", design_name=design_name, run_dir=run_dir, fix_strategy=fix_strategy)

    def run_fix_leakage(self, design_name: str, run_dir: str, fix_strategy: str) -> dict:
        return self._execute("run_fix_leakage", design_name=design_name, run_dir=run_dir, fix_strategy=fix_strategy)

