from __future__ import annotations

from typing import Protocol

# 10 个 step 的唯一注册表（单一事实源）：
# config.yaml.step_command 的键必须是这里的子集；
# mcp_app.py 的 @tool 注册与这里一一对应。
STEP_NAMES: tuple[str, ...] = (
    "run_eco_route",
    "run_ext",
    "run_sta",
    "run_pv",
    "run_signoff",
    "run_pt_fix_setup",
    "run_pt_fix_hold",
    "run_pt_fix_leakage",
    "run_pt_fix_drv",
    "run_xtop_fix_hold",
)


class ECOMCPServer(Protocol):
    def run_eco_route(self, design_name: str, run_dir: str) -> dict: ...
    def run_ext(self, design_name: str, run_dir: str) -> dict: ...
    def run_sta(self, design_name: str, run_dir: str) -> dict: ...
    def run_pv(self, design_name: str, run_dir: str) -> dict: ...
    def run_signoff(self, design_name: str, run_dir: str) -> dict: ...
    def run_pt_fix_setup(self, design_name: str, run_dir: str, fix_strategy: str) -> dict: ...
    def run_pt_fix_hold(self, design_name: str, run_dir: str, fix_strategy: str) -> dict: ...
    def run_pt_fix_leakage(self, design_name: str, run_dir: str, fix_strategy: str) -> dict: ...
    def run_pt_fix_drv(self, design_name: str, run_dir: str, fix_strategy: str) -> dict: ...
    def run_xtop_fix_hold(self, design_name: str, run_dir: str, fix_strategy: str) -> dict: ...
