from __future__ import annotations

from typing import Protocol


class ECOMCPServer(Protocol):
    def run_eco_route(self, design_name: str, run_dir: str) -> dict: ...
    def run_ext(self, design_name: str, run_dir: str) -> dict: ...
    def run_sta(self, design_name: str, run_dir: str) -> dict: ...
    def run_pv(self, design_name: str, run_dir: str) -> dict: ...
    def run_signoff(self, design_name: str, run_dir: str) -> dict: ...
    def run_fix_setup(self, design_name: str, run_dir: str, fix_strategy: str) -> dict: ...
    def run_fix_hold(self, design_name: str, run_dir: str, fix_strategy: str) -> dict: ...
    def run_fix_leakage(self, design_name: str, run_dir: str, fix_strategy: str) -> dict: ...
